version: '3.8'

services:
  backend:
    image: rahma324ssalah/unique-x-backend:latest
    container_name: unique-x-backend
    restart: always
    ports:
      - "5000:80"
    environment:
      # ركزي هنا: غيرنا الـ IP لـ IP السيرفر واسم الداتابيز لـ Betk
      - ConnectionStrings__DefaultConnection=Server=37.60.230.225;Database=Betk;User=sa;Password=ABDO@menna2026;TrustServerCertificate=True;

      - CloudinarySettings__CloudName=${CLOUDINARY_CLOUD_NAME}
      - CloudinarySettings__ApiKey=${CLOUDINARY_API_KEY}
      - CloudinarySettings__ApiSecret=${CLOUDINARY_API_SECRET}
      - JWT__Key=${JWT_KEY}

      - FrontendUrl=https://betk.property
      - EmailSettings__Email=uniquexxxxxxx@gmail.com
      - EmailSettings__Password=xntbkmlhejfxwmhg
      - EmailSettings__Host=smtp.gmail.com
      - EmailSettings__Port=587

  frontend:
    image: rahma324ssalah/unique-x-frontend:latest
    container_name: unique-x-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend