name: Deploy to Contabo

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Backend
        uses: docker/build-push-action@v4
        with:
          context: "./Unique X"
          file: "./Unique X/Dockerfile"
          push: true
          tags: rahma324ssalah/unique-x-backend:latest
          no-cache: true

      - name: Build and Push Frontend
        uses: docker/build-push-action@v4
        with:
          context: "./Unique X/frontend/UniqueXApp"
          file: "./Unique X/frontend/UniqueXApp/Dockerfile"
          push: true
          tags: rahma324ssalah/unique-x-frontend:latest
          no-cache: true

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            # Frontend
            docker pull rahma324ssalah/unique-x-frontend:latest
            docker stop unique-x-frontend || true
            docker rm unique-x-frontend || true
            docker run -d \
              --name unique-x-frontend \
              --restart unless-stopped \
              -p 3000:80 \
              rahma324ssalah/unique-x-frontend:latest

            # Backend
            docker pull rahma324ssalah/unique-x-backend:latest
            docker stop unique-x-backend || true
            docker rm unique-x-backend || true
            docker run -d \
              --name unique-x-backend \
              --restart unless-stopped \
              -p 5000:8080 \
              -e "JWT__Key=${{ secrets.JWT_KEY }}" \
              -e "JWT__Issuer=UniqueX" \
              -e "JWT__Audience=UniqueXUsers" \
              -e "ConnectionStrings__DefaultConnection=Server=37.60.230.225;Database=Betk;User=sa;Password=ABDO@menna2026;TrustServerCertificate=True;" \
              -e "CloudinarySettings__CloudName=${{ secrets.CLOUDINARY_CLOUD_NAME }}" \
              -e "CloudinarySettings__ApiKey=${{ secrets.CLOUDINARY_API_KEY }}" \
              -e "CloudinarySettings__ApiSecret=${{ secrets.CLOUDINARY_API_SECRET }}" \
              -e "AdminSettings__Email=admin@betk.property" \
              -e "AdminSettings__Password=Admin@123456" \
              rahma324ssalah/unique-x-backend:latest